# Config for node 5 - this is node2's replica.

port=6383
wal.path=wal/node5.wal
snapshot.path=snapshots/node5.snapshot

# ===== Phase 6: replication role =====
role=replica

master.host=172.19.224.1
master.port=6380
