# Config for node3b - the 2nd member of Shard 3's 3-node Raft group.
# See node1.properties for the full explanation of every key below.

port=6384
wal.path=wal/node3b.wal
snapshot.path=snapshots/node3b.snapshot

cluster.self=node3
cluster.nodes=node1:172.19.224.1:6379:0-5460,node2:172.19.224.1:6380:5461-10922,node3:172.19.224.1:6381:10923-16383

raft.self=node3b
raft.port=7384
raft.peers=node3:127.0.0.1:7381,node3c:127.0.0.1:7387
