# Config for node2c - the 3rd member of Shard 2's 3-node Raft group.
# See node1.properties for the full explanation of every key below.

port=6386
wal.path=wal/node2c.wal
snapshot.path=snapshots/node2c.snapshot

cluster.self=node2
cluster.nodes=node1:172.19.224.1:6379:0-5460,node2:172.19.224.1:6380:5461-10922,node3:172.19.224.1:6381:10923-16383

raft.self=node2c
raft.port=7386
raft.peers=node2:127.0.0.1:7380,node2b:127.0.0.1:7383
