# Config for node 6 - this is node3's replica.

port=6384
wal.path=wal/node6.wal
snapshot.path=snapshots/node6.snapshot

# ===== Phase 6: replication role =====
role=replica

master.host=172.19.224.1
master.port=6381
